[build.environment]
HUGO_VERSION = "0.119.0"

[build]
publish = "public/"

[context.production]
command = "hugo version; hugo --minify"

[context.deploy-preview]
command = "hugo version; hugo --buildFuture --buildDrafts --baseURL $DEPLOY_PRIME_URL"
